### ISSUE TITLE
Loaded advancement log spam

### ISSUE THREAD

**Issue by jonask028** [Stardust-Labs-MC/Incendium#13]
https://mclo.gs/8e0lSSh < game log

Scroll to line 24000 and youll see it leads advancments, forgets about multiple from incendium, loads the same amount of advancements minus the number of forgotten ones once, then goes back to loading them all. The cycle repeats until the log hits 100000 lines.

**Comment by catter1** [comment]
This does not appear to be caused by Incendium. Does the same thing occur when only Incendium is loaded? My guess is that another mod is messing with advancements.

**Comment by catter1** [comment]
Closing due to no response. Feel free to reopen the issue if it presists.
