### ISSUE TITLE
Chunk ban with Nether Castles

### ISSUE THREAD

**Issue by Pronana** [Stardust-Labs-MC/Incendium#15]
Using the newest version of Incendium on a Fabric server, my friends and I went to a Nether Castle, and got chunkbanned. We narrowed the culprit down to the Piglin snipers in the tower, when you get close to them they appear to spawn an enderpearl, and that pearl for some reason crashes the whole server and chunkbans everyone.

**Comment by catter1** [comment]
This is actually an issue with Auditory - you can view the ongoing issue [here](https://github.com/Sydokiddo/auditory/issues/32).

For now, as stated in the issue, disabling ender pearl sounds will fix it.
