### ISSUE TITLE
Is datapack removal without world reset supposed to be possible?

### ISSUE THREAD

**Issue by Kan0Shuuya** [Stardust-Labs-MC/Incendium#37]
When I try to remove Incendium datapack from my Paper server (git-Paper-491)
 (both via /datapack disable and direct .zip removal), the server cannot load anymore and throws _java.lang.RuntimeException: No key preset in MapLike..._ The issue is present even when I remove world_nether folder. Is this a bug? Am I supposed to remove main world folder too?

**Comment by catter1** [comment]
This is not a bug. When worldgen datapacks add biomes, they get stored in your `level.dat`. Removing the datapack does not automatically remove them from the registry.

To fix this issue, you will need to manually remove the Incendium biome entries from your `level.dat`. (Later, we will have tools to help you with this.). If you would like to figure it out on your own, you can investigate using third-party tools such as Misode's **NBT Viewer** extension for VSCode, or the **NBT Explorer** app.

If you would like someone to do it for you, join the [discord](https://discord.gg/stardustlabs) and upload your `level.dat` asking for help.
