### ISSUE TITLE
Whether it can be adapted to the Folia server as soon as possible

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [Stardust-Labs-MC/Incendium#39]
Hi, I am a user of the Folia server, I am trying to make Folia run in a productivity environment, this is unique, I would like to see if you can make this packet consider adapting to the Folia server, all server players love your packet, but because Folia disabled the server function directive so he cannot run on Folia, which is essential for my work, thank you!

**Comment by catter1** [comment]
No - there is nothing I can do about it. Folia is still extremely under development- the only datapacks that currently work are ones with no functions. Incendium relies on functions.

I do not recommend using Folia until it becomes more stable with its essential features - but if you do, you should not expect any function datapack functionality whatsoever.

**Comment by xiaoyueyoqwq** [comment]
> No - there is nothing I can do about it. Folia is still extremely under development- the only datapacks that currently work are ones with no functions. Incendium relies on functions.
> 
> I do not recommend using Folia until it becomes more stable with its essential features - but if you do, you should not expect any function datapack functionality whatsoever.

Okay, maybe you're right, but in my opinion everything has to start with, just like Folia or Windows InsiderProgram, and if no one wants to use it then these plugin developers won't get timely feedback, and finally thank you for your suggestions ❤️

**Comment by catter1** [comment]
> > No - there is nothing I can do about it. Folia is still extremely under development- the only datapacks that currently work are ones with no functions. Incendium relies on functions.
> > 
> > I do not recommend using Folia until it becomes more stable with its essential features - but if you do, you should not expect any function datapack functionality whatsoever.
> 
> Okay, maybe you're right, but in my opinion everything has to start with, just like Folia or Windows InsiderProgram, and if no one wants to use it then these plugin developers won't get timely feedback, and finally thank you for your suggestions ❤️

Perhaps I wasn't clear - to the best of my knowledge (correct me if I'm wrong), it is physically impossible to get datapacks working on Folia yet. There is nothing on the datapack side that can be done to "add compatibility with Folia" - that is simply not a thing. This all needs to be done on Folia's side.

**Comment by xiaoyueyoqwq** [comment]
> > > No - there is nothing I can do about it. Folia is still extremely under development- the only datapacks that currently work are ones with no functions. Incendium relies on functions.
> > > 
> > > I do not recommend using Folia until it becomes more stable with its essential features - but if you do, you should not expect any function datapack functionality whatsoever.
> > 
> > Okay, maybe you're right, but in my opinion everything has to start with, just like Folia or Windows InsiderProgram, and if no one wants to use it then these plugin developers won't get timely feedback, and finally thank you for your suggestions ❤️
> 
> Perhaps I wasn't clear - to the best of my knowledge (correct me if I'm wrong), it is physically impossible to get datapacks working on Folia yet. There is nothing on the datapack side that can be done to "add compatibility with Folia" - that is simply not a thing. This all needs to be done on Folia's side.

Yes, because Folia directly disables functions and packet instructions, packets that require functions will simply become unavailable, but I've tried some terrain packets that don't rely much on functions, and he works fine, of course, I'm weird about that
