### ISSUE TITLE
[Bug] light bug on floor of quartz flats biome

### ISSUE THREAD

**Issue by Thefatsparrow** [Stardust-Labs-MC/Incendium#47]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v5.3.0

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

light bug on floor of quartz only happens to quartz as my testing tells but i think the bug has something to do with shadows.

if you haven't noticed default minecraft no shaders there is no shadow in the nether. and with shaders the bug is annoying (see picture) because the shader is trying to generate a shadow even though there is no sun for it. so the bug is an annoying box surrounding you with shaders and without there is a shadow that should not even be there
![2023-07-10_21 27 44](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/0496713c-4a7f-4524-8e67-5edffaed33e9)

![2023-07-10_21 26 44](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/ca232ffd-5108-4169-851a-55a1a27a023e)

**Comment by ChoiceTheorem** [comment]
Doesn't sound remotely like Incendium's issues. More like your graphic mods.

**Comment by Thefatsparrow** [comment]
tested on fresh install aswell still same thing

**Comment by Thefatsparrow** [comment]
tested with only mod being incedium so ye it aint my graphic mods lol

**Comment by catter1** [comment]
Incendium can physically not cause this. It is a client-side issue.

**Comment by Thefatsparrow** [comment]
fresh install and theres still a shadow there causing bugs

only happens with incedium there should not be a shadow in the nether

maybe do some testing before jumping to conclusions :)
![2023-07-12_18 54 06](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/d7f387a7-4c94-41b8-97a2-7c6cdf732e17)
![2023-07-12_18 53 39](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/fe6b257a-49a6-4d6f-a020-e539fca6b797)
![2023-07-12_18 53 43](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/52646879-4ffa-45aa-9da5-2ec457241728)
