### ISSUE TITLE
[Bug] lava being cut off by structures means bugged lava

### ISSUE THREAD

**Issue by Thefatsparrow** [Stardust-Labs-MC/Incendium#48]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v5.3.0

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

lava being cut off by structures (see picture)
![2023-07-10_21 26 29](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/ea9bcf2b-513a-4db0-af72-f6b72509c14c)

### Additional context

and more lighting bugs for you! as you can see by the image

**Comment by catter1** [comment]
This bug of lava being cut off is valid, you can keep it open

**Comment by Thefatsparrow** [comment]
darn so you close all my others and i try to close my other one cause its not valid and then you go and re open it lol

**Comment by Thefatsparrow** [comment]
im closing this one because im going to add a new issue with more details and more pictures so keep this one clsoed while i get the information for the new one
