### ISSUE TITLE
[Bug] light bug on quartz 

### ISSUE THREAD

**Issue by Thefatsparrow** [Stardust-Labs-MC/Incendium#49]
### What Minecraft version(s) does this apply to?

1.20

### Project version

5.3.0

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

lighting bug that only happens with incedium which causes shadows and bugs.

there should not be a shadow in the nether

its not a client issue i  already know thats a fact 

![2023-07-12_18 54 06](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/4ee3f26d-2507-427e-acd8-ef5a257785a0)
![2023-07-12_18 53 39](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/47e99d44-79e1-490a-b617-40742761c307)
![2023-07-12_18 53 43](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/263eb97b-76bc-4e9d-8a16-02d81484905e)

### Additional context

tested on fresh install see picture 

maybe test before jumping to conclusions and closing my last issue :)

**Comment by catter1** [comment]
Incendium can physically not cause this issue. It is impossible. Stop creating duplicate issues.
