### ISSUE TITLE
[Bug] structures cutting off lava and making ugly walls

### ISSUE THREAD

**Issue by Thefatsparrow** [Stardust-Labs-MC/Incendium#50]
### What Minecraft version(s) does this apply to?

1.20

### Project version

5.3.0

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

structures cutting off walls and lava see images
![2023-07-12_22 03 22](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/047c1a79-c5d6-46fa-96ab-5426b88d8169)
![2023-07-12_22 03 08](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/f98f4cf8-a779-49b7-a298-c1a8c70acd2b)
![2023-07-12_22 01 31](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/2bdf1fbb-5c53-4e52-8166-d54b4cbcf8a9)

![2023-07-12_22 02 55](https://github.com/Stardust-Labs-MC/Incendium/assets/86117177/8d779b33-1edd-4549-8496-55d7da84059c)

**Comment by Thefatsparrow** [comment]
this problem still not fixed? lol it makes the mod unusable in 1.20

**Comment by Apollounknowndev** [comment]
This is just due to how structures work and cannot be fixed. It looks kinda strange, but calling the mod _unusable_ because of it is... just incorrect? Everything works, the structure placement just looks wonky in some cases.

**Comment by naomieow** [comment]
This issue can be closed as invalid @catter1

**Comment by catter1** [comment]
For *now*, the last improvement to this has been made in 5.3.4. This will be revisted later in the rework.
