### ISSUE TITLE
[Bug] Sanctum Guards not spawning

### ISSUE THREAD

**Issue by eyelaseringkindofway** [Stardust-Labs-MC/Incendium#53]
### What Minecraft version(s) does this apply to?

1.20

### Project version

5.3.1

### Mod or datapack version?

Datapack

### Describe the bug

So I have already reported this problem on PlanetMinecraft but I thought here would be better.

I think I've discovered a problem with one of the structures in the game but I am not sure if it is intentional. We have a server with this datapack and we have raided almost 5 Sanctums now.
The problem there are barely any vindicators, evokers, or pillagers to be seen anywhere. I remember playing this pack in older versions and in the main hall of the church there would a horde of Illagers and there would also be some defending the dungeon under the church. So for the past few Sanctums me and my friends have raided there have been absolutely no resistance and we kinda just walked around looting the dungeon.
Was wondering if it was intentional to remove all enemies in the Sanctum or there's been a problem when upgrading to 1.20.
Thanks (Please ignore the pillagers its a texture pack).

<img width="1440" alt="Screen Shot 2023-07-28 at 11 22 02 PM" src="https://github.com/Stardust-Labs-MC/Incendium/assets/79093593/369eff52-b6b7-48a4-98a3-da3b49087517">
<img width="1440" alt="Screen Shot 2023-07-28 at 11 22 35 PM" src="https://github.com/Stardust-Labs-MC/Incendium/assets/79093593/2706ad37-2c5e-49e0-b8da-259ebd570f1d">
<img width="1440" alt="Screen Shot 2023-07-28 at 11 22 22 PM" src="https://github.com/Stardust-Labs-MC/Incendium/assets/79093593/8a40d4c2-43b4-488a-b031-d75a7bd37dda">

### Additional context

In the vault room where you kill the Pillagers with the Holy Wrath. Those still spawn, no other Illager spawns other than those 3 guys. I've checked the update logs as well it doesn't seem this change was wrote anywhere so I assume its bug. I really hope this gets fixed because the Sanctum is really boring right now.

**Comment by catter1** [comment]
Was this Sanctum generated before or after you updated to 5.3.1? Because if was generated in 5.3.0, then the bug of them despawning would still apply unfortunately

**Comment by eyelaseringkindofway** [comment]
> Was this Sanctum generated before or after you updated to 5.3.1? Because if was generated in 5.3.0, then the bug of them despawning would still apply unfortunately

The server was made when 1.20.1 came out and when Incendium came out we deleted our old nether world, twice. Both times we had the issue of the guards not spawning

**Comment by catter1** [comment]
Was not able to reproduce; if this is stll an issue, reopen it with details on how to do so.
