### ISSUE TITLE
[Bug] Infinite corridor not working in Sanctums

### ISSUE THREAD

**Issue by Clayrok** [Stardust-Labs-MC/Incendium#57]
### What Minecraft version(s) does this apply to?

1.20

### Project version

5.3.1

### Mod or datapack version?

Datapack

### Describe the bug

The infinite corridor doesn't activate properly. Only 2 blocks come out of the wall.

Repro rate: 100% (Every Sanctum)

Repro steps:
- Find an infinite corridor
- Walk on the pressure plate in front of the dispenser

Result:
Only 2 blocks come out of the wall.

Expected:
An entire fake wall come out of the wall giving the illusion of an infinite looping corridor.

![2023-09-14_04 51 47](https://github.com/Stardust-Labs-MC/Incendium/assets/48133135/8e978bcf-e669-4244-b6a7-99e2b3376e7d)

**Comment by catter1** [comment]
Will take a look at it - no guarentee on when this will be fixed due to how many other projects I have atm

**Comment by catter1** [comment]
fixed in v5.3.3
