### ISSUE TITLE
[Bug] Infinite trigger of special shield ability

### ISSUE THREAD

**Issue by Joboblock** [Stardust-Labs-MC/Incendium#60]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v5.3.1

### Mod or datapack version?

Datapack

### Describe the bug

By shooting an arrow into the air, walking back a little and blocking with a special shield (e.g. Prismatic, Necrotic, Radiation) into the direction of the arrow, the special effect of the shields will be triggered multiple times. This can be even easier reproduced by spawning the arrow with commands or creating a redstone contraption to place the arrow more precisely.

**Comment by catter1** [comment]
fixed (potentially) in v5.3.3
