### ISSUE TITLE
1.18.2. Failed to validate datapack

### ISSUE THREAD

**Issue by radiocannot** [Stardust-Labs-MC/Incendium#7]
Get this in my latest.log when trying to add or remove a datapack(also worlds won't create cuz of this)

"Failed to validate datapack

java.util.concurrent.CompletionException: com.google.gson.JsonParseException: Error(s) loading registries:

Error(s) loading registry minecraft:worldgen/biome:
Optional field "particle" was invalid: No key color in MapLike[{"type":"minecraft:dust","r":0.9,"g":0.6,"b":0.4,"scale":1}]
	at: "effects"
	at: file "data/incendium/worldgen/biome/infernal_dunes.json"
	at: data pack Fabric Mods"

if i remove the
"particle": {
      "options": {
        "type": "minecraft:dust",
        "r": 0.9,
        "g": 0.6,
        "b": 0.4,
        "scale": 1
      },
      "probability": 0.004
    }
field in the json file datapack validates

**Comment by radiocannot** [comment]
fixed by replacing the "r g b" parameters with a proper "color" parameter:
"color": [
          0.9,
          0.6,
          0.4
],
(look toxic_heap.json for reference)

**Comment by catter1** [comment]
Apologies for not seeing this issue - this conflict with Cyanide was actually fixed in Incendium 5.1.4. Now, if you're using 1.18.2 and 5.0.6, I don't *believe* the fix was included in that version, but it will for sure be in the future 5.0.7 version.

Thanks for the issue creation, though!
