### ISSUE TITLE
Incendium causing Console to spam numbers when players are in the Nether

### ISSUE THREAD

**Issue by dookielations** [Stardust-Labs-MC/Incendium#70]
### What Minecraft version(s) does this apply to?

1.20

### Project version

1.20.4 v5.4.3

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

When players are in the Nether the console spams numbers, especially "0"
I have Incendium and RegionsUnexplored running on the mc server 1.20.1 (fabric launcher)

### Additional context

[16:35:22] [Server thread/INFO]: dookielations has made the advancement [Hellish Paradise]
[16:35:22] [Server thread/INFO]: dookielations has made the advancement [Strange Biomes]
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

**Comment by catter1** [comment]
Please don't duplicate a support question both on Github and on Discord. Since I already answered you on Discord, and I will likely reply slightly faster there, I will close this issue so we can continue on Discord.
