### ISSUE TITLE
[Bug] Pipeline structure causes extreme fps drops due to pipeline sentry dust particles

### ISSUE THREAD

**Issue by Simple205** [Stardust-Labs-MC/Incendium#75]
### What Minecraft version(s) does this apply to?

1.20

### Project version

1.20.1_v5.3.1

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

Whenever a pipeline structure loads fps drops dramatically from 350 fps down to no more than 45 fps. Ive found that disabling redstone dust particles fixes this and the source of these particles comes from the custom blaze mobs. This is a pretty big issue as this mod becomes practically unplayable without disabling the redstone dust particles which isn't ideal and I would prefer to leave them enabled.

### Additional context

I'm using fabulously optimized with Incendium.

**Comment by catter1** [comment]
This will be addressed during the rewrite
