### ISSUE TITLE
[Bug] Hazmat suit doesn't protect all poison

### ISSUE THREAD

**Issue by Symmettry** [Stardust-Labs-MC/Incendium#76]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v5.3.4

### Mod or datapack version?

Datapack

### Describe the bug

Hazmat suit doesn't protecting against poison as it says.

Putting it on and then (might be problem here) applying poison with /effect still damages you

### Additional context

i'm unsure if it's just caused by getting poison without survival means, but this bug also effects any plugins that give you poison (like mine)

**Comment by catter1** [comment]
Hazmat suit works by essentially doing `/effect clear @s minecraft:poison`. In Vanilla, this seems to work fine. Could be a plugin issue.

**Comment by Symmettry** [comment]
Yeah i forgot I had this open, i apparently had to run /function incendium:load or smth
