### ISSUE TITLE
[Bug] Voltaic Trident not working properly

### ISSUE THREAD

**Issue by quocnam201010** [Stardust-Labs-MC/Incendium#80]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v5.3.4

### Mod or datapack version?

Datapack

### Describe the bug

Voltaic Trident not working properly.
https://github.com/Stardust-Labs-MC/Incendium/assets/132324546/30bbcc6e-e45c-4d48-9f58-0f11a5ebe501

### Additional context

 Only happens in 1.20. Versions for Minecraft below 1.19.4 still works.

**Comment by quocnam201010** [comment]
Also tested on a vanilla server, still does not work.

**Comment by catter1** [comment]
This got fixed in the 5.3.5 dev version (#67) that will be releasing hopefully soon.
