### ISSUE TITLE
[Bug] Magma cube spawn and immediately despawn in toxic heap.

### ISSUE THREAD

**Issue by frosthuuund** [Stardust-Labs-MC/Incendium#82]
### What Minecraft version(s) does this apply to?

1.20

### Project version

5.3.5

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

Why is intended like this?

**Comment by catter1** [comment]
Yes, this is intentional. This is how we spawn the Toxic Slimes - magma cubes spawn, and are quickly replaced with the slimes. This is because it's one of the only options we have, but we have new ideas to manage it in the future rewrite.
