### ISSUE TITLE
we need 1.21!!!

### ISSUE THREAD

**Issue by dingshan1123** [Stardust-Labs-MC/Incendium#84]
### Describe your enhancement/improvement, with context and reasoning.

Our server needs it! It's really great！

**Comment by catter1** [comment]
I will be updated when it is updated

**Comment by dingshan1123** [comment]
How long will it be updated in the future？

**Comment by INSide-734** [comment]
> I will be updated when it is updated

I've been waiting for this for too long.😥😥
