### ISSUE TITLE
[Bug]: Vanilla Farms Broken

### ISSUE THREAD

**Issue by Fyoncle** [Stardust-Labs-MC/Incendium#87]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v5.3.5 ~ 1.20.x

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

Things like gold farms don't perform as expect, and since incendium spawns bedrock SO MUCH ABOVE we also got limited space to build some farms bc of the build limit, is there any workaround for that? im confused.

**Comment by catter1** [comment]
This is intentional. You are meant to adapt your gold farm design. If you want to extend the build height, we have a configuration guide for that in our Discord. I saw you in there earlier today, so I will redirect you there instead of copy/pasting it here. Do `/faq faq:Configuration` to view it.

**Comment by Fyoncle** [comment]
> This is intentional. You are meant to adapt your gold farm design. If you want to extend the build height, we have a configuration guide for that in our Discord. I saw you in there earlier today, so I will redirect you there instead of copy/pasting it here. Do `/faq faq:Configuration` to view it.

Yeah that issue was opened before i find the solution on discord, my bad.
