### ISSUE TITLE
Bow texture is missing

### ISSUE THREAD

**Issue by CSMMaster** [Stardust-Labs-MC/Incendium#88]
### What Minecraft version(s) does this apply to?

1.20

### Project version

Incendium_1.20.x_v5.3.5

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

It seems some of the textures are missing. Also, @Incendium does not bring up any listings in the menu.

**Comment by catter1** [comment]
To see the textures, you need our resourcepack [Sparkles](https://modrinth.com/resourcepack/sparkles).

What do you mean by the comment about the menu listings? I'm not sure I understand.

**Comment by CSMMaster** [comment]
Thank you for confirming the resource pack requirement.

When referencing the menu, I am referring to the crafting menu when in a player’s inventory. To find items from a mod, a user will type “@techreborn” in the search bar. This same method did not work when I typed “@incendium”. I hope this helps to clarify.

**Comment by catter1** [comment]
I was not aware of being able to type mod namespaces following an `@` to filter items.

Anyways, Incendium does not actually add custom items. The mod version of Incendium is just the datapack with `.jar` at the end. Therefore, they are not actually registered as separate items in the game, and will not show up in any item menus (JEI, REI, etc). Incendium doesn't have any crafting recipes at all (expect a single smithing table one), so nothing will show up there either.

**Comment by CSMMaster** [comment]
That explains the lack of recipes 🤣 Thank you for the clarification.
