### ISSUE TITLE
[Bug][1.21]At 1.21, when using Chilling Blade to attack certain entities (especially players), the deceleration effect will not trigger properly

### ISSUE THREAD

**Issue by dingshan1123** [Stardust-Labs-MC/Incendium#89]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v5.4.0

### Mod or datapack version?

Datapack

### Describe the bug

I originally thought it was a mechanism, but after checking the packet code, I found that it should be a bug

**Comment by dingshan1123** [comment]
Because there is no 1.21 option, we can only choose 1.20, which was actually tested under 1.21

**Comment by catter1** [comment]
The 1.21 port of Incendium is clearly marked as unsupported, and we will not be fixing any issues that arise from it.
