### ISSUE TITLE
[Bug]There is an error in the 'data \ advancement \ advancement \ infernal-dunes \ inferno \ armored_wings.json' file

### ISSUE THREAD

**Issue by fuuuuuuuuuuuuuuck** [Stardust-Labs-MC/Incendium#90]
### What Minecraft version(s) does this apply to?

1.20

### Project version

1.21 v540

### Mod or datapack version?

Datapack

### Describe the bug

requirement error,"minecraft:custom_data": "{incendium:{id:'infernal_wings'}}" should be "minecraft:custom_data": "{incendium:{item:'infernal_wings'}}".
Because in the game, the custom_data of this item is "{{incendium:{item:'infernal_wings'}}"

**Comment by catter1** [comment]
Thanks for the report, but just so you are aware, we are unlikely to fix it any time soon. The 1.21 port is marked as unsupported due to us focusing on the future rewrite.
