### ISSUE TITLE
[Enhancement] Matrix room

### ISSUE THREAD

**Issue by Anvil5465** [Stardust-Labs-MC/Incendium#93]
### Describe your enhancement/improvement, with context and reasoning.

It would be nice to have a [matrix](https://matrix.org/) chat room for people who want to be more involved in the project but who don't want to or can't use Discord. I have tried to make a Discord account, but unfortunately they require phone number verification and I use a VOIP number which is not accepted. It is counter-intuitive for an open source project to use proprietary software for communication anyway.

**Comment by catter1** [comment]
Incendium is not open source, but instead source available. (Exact license [here](https://github.com/Stardust-Labs-MC/license)) We do not accept outside contributions expect in rare cases, and just have the source on Github for people to view at their own leisure. Instead, we have a very small team that works on the project. The discord is for people to get assistance/support with getting the datapack to work on their worlds, give any suggestions, or just hang out.

Having a link between our discord and a matrix or some sort of other irc is possible in the future, but I haven't felt a need for it yet.
