### ISSUE TITLE
Plans for 1.21 rewrite

### ISSUE THREAD

**Issue by WitoldChmielowiec** [Stardust-Labs-MC/Incendium#95]
### Describe your enhancement/improvement, with context and reasoning.

What is the current status of the 1.21 rewrite? Is it coming in the next few weeks or I'm waiting for nothing :)?

**Comment by catter1** [comment]
No ETA - will not be ready soon. If you need a temporary port of Incendium for 1.21, we have it on [our website](https://www.stardustlabs.net/version-library).

**Comment by WitoldChmielowiec** [comment]
thx, didnt know that the verion even existed
