### ISSUE TITLE
[Bug] - looped error in console while playing

### ISSUE THREAD

**Issue by gh0stmustard** [Stardust-Labs-MC/Incendium#96]
### What Minecraft version(s) does this apply to?

1.19 - 1.19.3

### Project version

5.1.6

### Mod or datapack version?

Neoforge/Forge Mod

### Describe the bug

Console/log being spammed constantly with the following entries

```
[23:43:25] [Render thread/INFO] [minecraft/AdvancementList]: Forgot about advancement incendium:technical/on_player_hurt

[23:43:25] [Render thread/INFO] [minecraft/AdvancementList]: Forgot about advancement incendium:technical/on_player_hurt

[23:43:25] [Render thread/INFO] [minecraft/AdvancementList]: Forgot about advancement incendium:technical/root
```

### Additional context

I've deleted my advancements file and started fresh, still getting the same errors, but it was crashing my game before I deleted the possibly corrupt file.

Also seeing this in the logs now

`[00:33:47] [Render thread/WARN] [minecraft/AdvancementList]: Told to remove advancement incendium:technical/on_inventory_change but I don't know what that is`

**Comment by catter1** [comment]
We are unsure of what causes that issue. It has appeared randomly for people, with seemingly no rhyme or reason (even to myself). However, it doesn't seem to cause any issues... rather just a very annoying console spam. If your game crashed, I'd be unsure to say the "advancement issue" is what caused it. But if you send the entire log file using https://mclo.gs, I can take a look.

**Comment by IsriusQQ** [comment]
Hello, sorry to re-open such an old thread, I am encountering the same issue. 

I have uploaded my log file below. 
### latest.log: https://mclo.gs/KHR8uKK
### crash_assistant_app.log: https://mclo.gs/LIT9Lav
### win_event1778642369226.txt: https://mclo.gs/XFVZvw8
```ansi
Found [2;34m1[0m log analysis results:
[2;34mWasClosedByWindows[0m in: win_event1778642369226.txt
```

### What Minecraft version(s) does this apply to?
1.21.11

### Project version
5.4.12

### Mod or datapack version?
Fabric version 0.19.2

### Behavior

I am seeing the same behavior as the original comment. 
```
[23:14:29] [Render thread/WARN]: Told to remove advancement incendium:technical/on_player_hurt but I don't know what that is
[23:14:29] [Render thread/INFO]: Loaded 1881 advancements
[23:14:45] [Render thread/INFO]: Loaded 1883 advancements
[23:15:29] [Render thread/INFO]: Forgot about advancement incendium:technical/on_player_hurt
[23:15:29] [Render thread/INFO]: Forgot about advancement incendium:technical/root
[23:15:29] [Render thread/WARN]: Told to remove advancement incendium:technical/on_player_hurt but I don't know what that is
```

I understand if this issue will not be investigated, thank you for your time.

**Comment by catter1** [comment]
It is an annoying log spam, but it does not cause any issues - it is safe to ignore. We are currently undergoing a rewrite of Incendium, which should indirectly fix this issue as a byproduct of redoing the internal systems.

**Comment by IsriusQQ** [comment]
> It is an annoying log spam, but it does not cause any issues - it is safe to ignore. We are currently undergoing a rewrite of Incendium, which should indirectly fix this issue as a byproduct of redoing the internal systems.

Thank you for your reply! I am glad to hear that you are working on this issue. 

Sorry, I should have specified in my earlier comment. Just to give more information, the game froze in the above log file, and I force quit. But as you said, the freeze / crash only occurs sometimes when reloading advancements, it may be caused by a different issue.

I think the advancement reloading loop was caused by fire tick dealing damage and triggering the on_player_hurt. 

Thank you again for your time!

**Comment by catter1** [comment]
If you send your full log file (using [mclogs](<https://mclo.gs/>) or another log uploading site), we can see if there's anything else potentially causing the issue.
