### ISSUE TITLE
[Bug]buggy code name for biome info

### ISSUE THREAD

**Issue by VaporeonScripts** [Stardust-Labs-MC/Incendium#99]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

5.4.4

### Mod or datapack version?

Neoforge/Forge Mod

### Describe the bug

![image](https://github.com/user-attachments/assets/7438e93b-a9f5-482e-90ff-c13ebe012c19)

### Additional context

modpack: neotech reborn (if needed)

**Comment by catter1** [comment]
You need to use our resourcepack [Sparkles](https://modrinth.com/resourcepack/sparkles) to fix the biome names

**Comment by VaporeonScripts** [comment]
is it on curseforge?

**Comment by catter1** [comment]
It is not - just Modrinth at the moment

**Comment by VaporeonScripts** [comment]
aight, will wait for cf release, as i cant use it without cf ver

**Comment by catter1** [comment]
At the moment we have no plans to upload to Curseforge - I say "at the moment" because a release is a potential possibility in the future. Curseforge is just an absolute pain to maintain on the developer's end, so it doesn't make sense to.
